Account/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
# from Account.views import *
# from Account import views
# from Account.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path("app/", include('acApp.urls')),
    path("", home, name="project_home")
]

acApp/urls.py
from django.urls import path
# from acApp import views
# from acApp.views import *
# from acApp.views import home, index,userinfo, user_login,user_logout,Register,update_user,user_details
from acApp.views import *
app_name = "acApp"

urlpatterns = [
    path("home/", home, name="home_view"),
    path("index/",  index, name="index"),
    path('userinfo/', userinfo, name="userinfo"),
    path('user_login/',user_login, name="user_login"),
    path('logout/', user_logout, name="user_logout"),
    path('register/', Register, name="register"),
    path('update_info/', update_user, name="update"),
    path('user_details/', user_details, name="user_details"),
    path('user_delete/<str:email>/', user_delete, name="user_delete"),


]

acApp/models.py
from django.db import models
from django.contrib.auth.models import User


class user_table(models.Model):
    fname = models.CharField(max_length=60)
    lname = models.CharField(max_length=60)
    email = models.EmailField()
    DOB = models.DateField()

    def __str__(self):
        return self.fname + " " + self.lname


class User_profileinfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_url = models.URLField(blank=True)
    profile_img = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return self.user.username


class User_details(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    address1 = models.CharField(max_length=255)
    address2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    date_of_birth = models.DateField()
    gender = models.CharField(max_length=10)
    country = models.CharField(max_length=50)
    postal_code = models.CharField(max_length=20)

    def __str__(self):
        return self.name

acApp/forms.py
from django import forms
from acApp.models import user_table, User_profileinfo
from django.contrib.auth.models import User


class myNewForm(forms.ModelForm):
    class Meta:
        model = user_table
        fields = '__all__'


class mynewFormTwo(forms.Form):
    protfolio = forms.URLField()
    email = forms.EmailField()



##########today##############
class userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "email", "password",)


class userforminfo(forms.ModelForm):
    class Meta:
        model = User_profileinfo
        fields = ("portfolio_url", "profile_img")

Account/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    return HttpResponse("I'm Project function!.............")

acApp/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse
from acApp.forms import myNewForm, mynewFormTwo, userform, userforminfo
from .models import User_details
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('acApp:user_login'))


def home(request):
    form = mynewFormTwo()
    if request.method == "POST":
        form = mynewFormTwo(request.POST)

        if form.is_valid():
            print("form validation is successfully completed")
            print("portfolio: " + form.cleaned_data["protfolio"])
            print("EMAIL: " + form.cleaned_data["email"])

    return render(request, "acApp/index.html", {"form": form})


@login_required
def index(request):
    form = myNewForm()
    if request.method == "POST":
        form = myNewForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect("home")
        else:
            print("FORM IS INVALID")
    con = {"text": "PRAVEEN , PRASANTH", "form": form}
    return render(request, "acApp/basic.html", con)


def userinfo(request):
    if request.method == "POST":
        user_form = userform(request.POST)
        profile_form = userforminfo(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password'])
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if "profile_img" in request.FILES:
                profile.profile_img = request.FILES["profile_img"]

            profile.save()

            return redirect("acApp:index")

        else:
            print("Your form is not valid!", user_form.errors, profile_form.errors)

    else:
        user_form = userform()
        profile_form = userforminfo()

    con = {'userform': user_form, 'userforminfo': profile_form}
    return render(request, "acApp/user_info.html", con)


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('passw')
        user = authenticate(username=username, password=password)

        if user:
            print(user.is_active)
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('acApp:index'))

            else:
                print("ACCOUNT IS NOT ACTIVE")
        else:
            print("Someone tried to logging and Failed !")
            print(f"username: {username} password: {password}")
            return HttpResponse("INVALID CREDENTIALS")

    else:
        return render(request, "acApp/user_login.html", {})

@login_required
def Register(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        dob = request.POST.get('dob')
        gender = request.POST.get('gender')
        city = request.POST.get('city')
        country = request.POST.get('country')
        address1 = request.POST.get('address1')
        address2 = request.POST.get('address2')
        postal_code = request.POST.get('pcode')

        user = User_details.objects.create(name=name
                                    ,email=email,address1=address1,address2=address2,city=city, phone=phone, date_of_birth=dob,gender=gender, country=country, postal_code=postal_code)
        if user:
            user.save()
            return HttpResponse("USER DETAILS SAVED TO DB!")
        print("USER DETAILS SAVED TO DB!")
    else:
        return render(request, "acApp/register.html")

@login_required
def update_user(request):
    if request.method == "POST":
        user_email = request.user.email
        print(user_email)
        user = get_object_or_404(User_details, email=user_email)
        user.name = request.POST.get('name')
        user.email = request.POST.get('email')
        user.phone = request.POST.get('phone')
        user.date_of_birth = request.POST.get('dob')
        user.gender = request.POST.get('gender')
        user.city = request.POST.get('city')
        user.country = request.POST.get('country')
        user.address1 = request.POST.get('address1')
        user.address2 = request.POST.get('address2')
        user.postal_code = request.POST.get('pcode')

        user.save()
        return HttpResponse("USER DETAILS UPDATED IN DB!")

    else:
        user_email = request.user.email
        print(user_email)
        user = get_object_or_404(User_details, email=user_email)
        print(user.gender)
        return render(request, "acApp/update.html", {"det": user})

@login_required
def user_details(request):
    print(request.user.username)
    u_name = request.user.username
    user_det = get_object_or_404(User, username=u_name)
    return render(request, "acApp/user_details.html", {"det": user_det, "s": u_name})


def user_delete(request, email):
    if request.method == "POST":
        user = get_object_or_404(User, email=email)
        user.delete()
        return HttpResponse("User deleted Successfully!!")
    else:
        return None

templates/acApp/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/reg.css' %}" rel="stylesheet">

    <!----===== Iconscout CSS ===== -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <script src="{% static 'css/script.js' %}"></script>

    <title></title>
</head>
<body>
<section>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>

      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'acApp:user_logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'acApp:user_login' %}">Login</a>
      </li>
      {% endif %}


      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
  </section>

{% block body_block %}
{% endblock %}

<footer class="text-center bg-body-tertiary">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        data-mdb-ripple-init
        class="btn btn-link btn-floating btn-lg text-body m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        data-mdb-ripple-init
        class="btn btn-link btn-floating btn-lg text-body m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        data-mdb-ripple-init
        class="btn btn-link btn-floating btn-lg text-body m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        data-mdb-ripple-init
        class="btn btn-link btn-floating btn-lg text-body m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        data-mdb-ripple-init
        class="btn btn-link btn-floating btn-lg text-body m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-linkedin"></i
      ></a>
      <!-- Github -->
      <a
        data-mdb-ripple-init
        class="btn btn-link btn-floating btn-lg text-body m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2020 Copyright:
    <a class="text-body" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

</body>
</html>

templates/acApp/basic.html
{% extends 'acApp/base.html' %}
{% block body_block %}
{% load static %}
<div class="container">
    <img src="{% static 'images/Kaduva.png' %}"><br><br>


<h1 class="text">{{text}}</h1>

<form method="POST" action="">
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Submit">
</form><br>
    <a href="{% url 'acApp:home_view' %}"><button class="btn btn-primary">Home</button></a>
</div>
{% endblock %}

templates/acApp/index.html
<!DOCTYPE html>
{% extends 'acApp/base.html' %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Please fill out the form!</h1>
        <form method="POST" action="">
              {%csrf_token%}
              {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="Submit">


        </form><br>

        <a href="{% url 'acApp:index' %}"><button class="btn btn-primary">Index</button></a>
    </div>
</div>

{% endblock %}

templates/acApp/register.html
{% extends 'acApp/base.html' %}
{% block body_block %}

    <section class="container">
      <header>Registration Form</header>
      <form action="{% url 'acApp:register' %}" method="POST" class="form">
        {% csrf_token %}
        <div class="input-box">
          <label>Full Name</label>
          <input type="text" placeholder="Enter full name" name="name" required />
        </div>

        <div class="input-box">
          <label>Email Address</label>
          <input type="text" placeholder="Enter email address" name="email" required />
        </div>

        <div class="column">
          <div class="input-box">
            <label>Phone Number</label>
            <input type="number" placeholder="Enter phone number" name="phone" required />
          </div>
          <div class="input-box">
            <label>Birth Date</label>
            <input type="date" placeholder="Enter birth date" name="dob" required />
          </div>
        </div>
        <div class="gender-box">
          <h3>Gender</h3>
          <div class="gender-option">
            <div class="gender">
              <input type="radio" id="check-male" name="gender" checked />
              <label for="check-male">male</label>
            </div>
            <div class="gender">
              <input type="radio" id="check-female" name="gender" />
              <label for="check-female">Female</label>
            </div>
            <div class="gender">
              <input type="radio" id="check-other" name="gender" />
              <label for="check-other">prefer not to say</label>
            </div>
          </div>
        </div>
        <div class="input-box address">
          <label>Address</label>
          <input type="text" placeholder="Enter street address" name="address1" required />
          <input type="text" placeholder="Enter street address line 2" name="address2" required />
          <div class="column">
            <div class="select-box">
              <select name="country">
                <option hidden>Country</option>
                <option value="America">America</option>
                <option value="Japan">Japan</option>
                <option value="India">India</option>
                <option value="Nepal">Nepal</option>
              </select>
            </div>
            <input type="text" placeholder="Enter your city" name="city" required />
          </div>
          <div class="column">
            <input type="text" placeholder="Enter your region" name="region" required />
            <input type="number" placeholder="Enter postal code" name="pcode" required />
          </div>
        </div>
        <button type="submit">Submit</button>
      </form>
    </section>


{% endblock %}

templates/acApp/update.html
{% extends 'acApp/base.html' %}
{% block body_block %}

    <section class="container">
      <header>Registration Form</header>
        {% if det %}
      <form action="{% url 'acApp:update' %}" method="POST" class="form">
        {% csrf_token %}
        <div class="input-box">
          <label>Full Name</label>
          <input type="text" placeholder="Enter full name" name="name" value="{{det.name}}" required />
        </div>

        <div class="input-box">
          <label>Email Address</label>
          <input type="text" placeholder="Enter email address" name="email" value="{{det.email}}"  required />
        </div>

        <div class="column">
          <div class="input-box">
            <label>Phone Number</label>
            <input type="number" placeholder="Enter phone number" name="phone" value="{{det.phone}}"  required />
          </div>
          <div class="input-box">
            <label>Birth Date</label>
            <input type="text" placeholder="Enter birth date" name="dob"  value="{{det.date_of_birth}}" required />
          </div>
        </div>
        <div class="gender-box">
          <h3>Gender</h3>
          <div class="gender-option">
            <div class="gender">
              <input type="radio" id="check-male" name="gender"  {% if det.gender == 'male' %}checked{% endif %} />
              <label for="check-male">male</label>
            </div>
            <div class="gender">
              <input type="radio" id="check-female" name="gender" {% if det.gender == 'female' %}checked{% endif %} />
              <label for="check-female">Female</label>
            </div>
            <div class="gender">
              <input type="radio" id="check-other" name="gender"  {% if det.gender == 'prefer_not_to_say' %}checked{% endif %} />
              <label for="check-other">prefer not to say</label>
            </div>
          </div>
        </div>
        <div class="input-box address">
          <label>Address</label>
          <input type="text" placeholder="Enter street address" name="address1" value="{{det.address1}}" required />
          <input type="text" placeholder="Enter street address line 2" name="address2" value="{{det.address2}}"  required />
          <div class="column">
            <div class="select-box">
              <select name="country">
                <option hidden>Country</option>
                <option value="America">America</option>
                <option value="Japan">Japan</option>
                <option value="India">India</option>
                <option value="Nepal">Nepal</option>
              </select>
            </div>
            <input type="text" placeholder="Enter your city" name="city" value="{{det.city}}" required />
          </div>
          <div class="column">
            <input type="text" placeholder="Enter your region" name="region" required />
            <input type="number" placeholder="Enter postal code" name="pcode" value="{{det.postal_code}}" required />
          </div>
        </div>
        <button type="submit">Submit</button>
      </form>
        {% endif %}
    </section>


{% endblock %}

templates/acApp/user_details.html
{% extends 'acApp/base.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>User details </h1>
        <table>
            <tr>
                <th style="padding:10px 10px 10px 10px;">username</th>
                <th style="padding:10px 10px 10px 10px;">email</th>
                <th style="padding:10px 10px 10px 10px;">Password</th>
            </tr>
            {% if det %}
            <tr>
                <td style="padding:10px 10px 10px 10px;">{{det.username}}</td>
                <td style="padding:10px 10px 10px 10px;">{{det.email}}</td>
                <td style="padding:10px 10px 10px 10px;" >{{det.password}}</td>
                <td>
                    <form action="{% url 'acApp:user_delete' email=det.email %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-primary" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
            {% endif %}
        </table>


    </div>
</div>


{% endblock %}

templates/acApp/user_info.html
{% extends 'acApp/base.html'%}
{% block body_block %}
<div class="container">
    <form method="POST" enctype="multipart/form-data" action="">
        {% csrf_token %}
        {{userform.as_p}}
        {{userforminfo.as_p}}
        <input type="submit" class="btn btn-primary" value="Submit">

    </form>
</div>


{% endblock %}

templates/acApp/user_login.html
{% extends 'acApp/base.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <form action="{% url 'acApp:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="username"> Username:</label>
            <input type="text" id="username" name="username" placeholder="USERNAME">
            <label for="password"> Password:</label>
            <input type="password" id="password" name="passw" placeholder="PASSWORD">
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</div>

{% endblock %}